### ISSUE TITLE
Add Functions Palette

### ISSUE THREAD

**Issue by jimkring** [tweeto/Simple-Progress-Bar#18]
Great tool! It would be nice if the API and Examples where in the Functions Palette. This configured in VIPM's package builder, here:

![image](https://user-images.githubusercontent.com/381432/82124066-8eabf280-9751-11ea-9fda-958f9919a362.png)

**Comment by nicolas-bats** [comment]
Hi Jim, adding functions palette is already planned in ticket #7 and will be released in `version 1.1` of the library.
